CREATE TABLE IF NOT EXISTS clientes(
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  lealdade INTEGER NOT NULL
);
  
CREATE TABLE IF NOT EXISTS enderecos(
  id BIGSERIAL PRIMARY KEY,
  cep VARCHAR(20) NOT NULL,
  rua VARCHAR(50) NOT NULL,
  numero INTEGER NOT NULL,
  bairro VARCHAR(50) NOT NULL,
  complemento VARCHAR(100),
  cliente_id INTEGER UNIQUE NOT NULL,
  CONSTRAINT cliente_id_fk FOREIGN KEY (cliente_id)
  REFERENCES clientes(id)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pedidos(
  id BIGSERIAL PRIMARY KEY,
  status VARCHAR(50) NOT NULL,
  cliente_id INTEGER NOT NULL,
  CONSTRAINT cliente_id_fk
  FOREIGN KEY (cliente_id)
  REFERENCES clientes(id)
  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS produtos(
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(100) UNIQUE NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  preco FLOAT NOT NULL,
  pts_de_lealdade INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos_pedidos(
  id BIGSERIAL PRIMARY KEY,
  pedido_id INTEGER NOT NULL,
  CONSTRAINT pedido_id_fk
  FOREIGN KEY (pedido_id) REFERENCES pedidos(id)
  ON UPDATE CASCADE ON DELETE CASCADE,
  produto_id INTEGER NOT NULL,
  CONSTRAINT produto_id_fk
  FOREIGN KEY (produto_id) REFERENCES produtos(id)
  ON UPDATE CASCADE ON DELETE CASCADE
);
